name: CI

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: goto-bus-stop/setup-zig@v2
        with:
          version: master
      
      - name: Install Wireguard
        run: |
            sudo apt update
            sudo apt install -f wireguard-tools wireguard-dkms -y && \
            sudo modprobe wireguard

      - name: build summary
        run: zig build -fsummary

      - name: run wireguard-zig
        run: sudo zig-out/bin/wireguard-zig
